import shutil
import subprocess
import os
import tempfile
import pkg_resources

js_files = [
    "/static/app/app.js",
    "/static/app/services.js",
    "/static/app/routes.js",
    "/static/app/globalInterceptor.js",
    "/static/app/multiPickerDirective.js",
    "/static/app/singlePickerDirective.js",
    "/static/app/kendoDraggableDirective.js",
    "/static/app/ckEditorDirective.js",
    "/static/app/reportingIntensityChartDirective.js",
    "/static/app/reportingConsumptionChartDirective.js",
    "/static/app/reportingTreeDirective.js",
    "/static/app/kendoTreeViewDirective.js",
    "/static/app/textReportDirective.js",
    "/static/app/peakReportDirective.js",
    "/static/app/home/homeCtrl.js",
    "/static/app/home/benchmarkPerformanceTableDirective.js",
    "/static/app/home/benchmarkBudgetVarianceTableDirective.js",
    "/static/app/home/notificationListDirective.js",
    "/static/app/home/notificationsCtrl.js",
    "/static/app/login/loginCtrl.js",
    "/static/app/users/usersListCtrl.js",
    "/static/app/users/usersDeleteCtrl.js",
    "/static/app/users/usersEditCtrl.js",
    "/static/app/users/usersNewCtrl.js",
    "/static/app/groups/groupTreeFactory.js",
    "/static/app/groups/groupsListCtrl.js",
    "/static/app/groups/groupsTreeCtrl.js",
    "/static/app/groups/groupTreeDirective.js",
    "/static/app/groups/groupsEditCtrl.js",
    "/static/app/groups/groupsDeleteCtrl.js",
    "/static/app/groups/groupsNewCtrl.js",
    "/static/app/weatherstations/weatherstationsListCtrl.js",
    "/static/app/weatherstations/weatherstationsEditCtrl.js",
    "/static/app/weatherstations/weatherstationsDeleteCtrl.js",
    "/static/app/weatherstations/weatherstationsNewCtrl.js",
    "/static/app/accounts/accountsListCtrl.js",
    "/static/app/accounts/accountsEditCtrl.js",
    "/static/app/accounts/accountsDeleteCtrl.js",
    "/static/app/accounts/accountsNewCtrl.js",
    "/static/app/equipment/equipmentListCtrl.js",
    "/static/app/equipment/equipmentEditCtrl.js",
    "/static/app/equipment/equipmentDeleteCtrl.js",
    "/static/app/equipment/equipmentNewCtrl.js",
    "/static/app/equipment/equipmentService.js",
    "/static/app/equipment/equipmentDashboardCtrl.js",
    "/static/app/roles/rolesDeleteCtrl.js",
    "/static/app/roles/rolesEditCtrl.js",
    "/static/app/roles/rolesListCtrl.js",
    "/static/app/roles/rolesNewCtrl.js",
    "/static/app/components/componentTreeFactory.js",
    "/static/app/components/componentsStructureTreeCtrl.js",
    "/static/app/components/componentsMappingTreeCtrl.js",
    "/static/app/components/componentsPointManagerCtrl.js",
    "/static/app/components/componentStructureTreeDirective.js",
    "/static/app/components/componentMappingTreeDirective.js",
    "/static/app/components/componentPointTreeDirective.js",
    "/static/app/components/componentsEngineeringManagerCtrl.js",
    "/static/app/categories/categoriesListCtrl.js",
    "/static/app/categories/categoriesNewCtrl.js",
    "/static/app/categories/categoriesEditCtrl.js",
    "/static/app/categories/categoriesDeleteCtrl.js",
    "/static/app/contacts/contactsDeleteCtrl.js",
    "/static/app/contacts/contactsEditCtrl.js",
    "/static/app/contacts/contactsListCtrl.js",
    "/static/app/contacts/contactsNewCtrl.js",
    "/static/app/tasks/tasksListCtrl.js",
    "/static/app/tasks/tasksNewCtrl.js",
    "/static/app/tasks/tasksDeleteCtrl.js",
    "/static/app/tasks/tasksEditCtrl.js",
    "/static/app/issues/issuesListCtrl.js",
    "/static/app/issues/issuesNewCtrl.js",
    "/static/app/issues/issuesEditCtrl.js",
    "/static/app/issues/issuesDeleteCtrl.js",
    "/static/app/projects/projectsDeleteCtrl.js",
    "/static/app/projects/projectsEditCtrl.js",
    "/static/app/projects/projectsNewCtrl.js",
    "/static/app/projects/projectsListCtrl.js",
    "/static/app/eco/ecoDeleteCtrl.js",
    "/static/app/eco/ecoEditCtrl.js",
    "/static/app/eco/ecoNewCtrl.js",
    "/static/app/eco/ecoListCtrl.js",
    "/static/app/committees/committeesListCtrl.js",
    "/static/app/committees/committeesNewCtrl.js",
    "/static/app/committees/committeesEditCtrl.js",
    "/static/app/committees/committeesDeleteCtrl.js",
    "/static/app/meetings/meetingsListCtrl.js",
    "/static/app/meetings/meetingsNewCtrl.js",
    "/static/app/meetings/meetingsDeleteCtrl.js",
    "/static/app/meetings/meetingsEditCtrl.js",
    "/static/app/meetingtypes/meetingtypesListCtrl.js",
    "/static/app/meetingtypes/meetingtypesNewCtrl.js",
    "/static/app/meetingtypes/meetingtypesDeleteCtrl.js",
    "/static/app/meetingtypes/meetingtypesEditCtrl.js",
    "/static/app/utilitycompanies/utilitycompaniesDeleteCtrl.js",
    "/static/app/utilitycompanies/utilitycompaniesEditCtrl.js",
    "/static/app/utilitycompanies/utilitycompaniesListCtrl.js",
    "/static/app/utilitycompanies/utilitycompaniesNewCtrl.js",
    "/static/app/actionitempriorities/actionitemprioritiesDeleteCtrl.js",
    "/static/app/actionitempriorities/actionitemprioritiesEditCtrl.js",
    "/static/app/actionitempriorities/actionitemprioritiesListCtrl.js",
    "/static/app/actionitempriorities/actionitemprioritiesNewCtrl.js",
    "/static/app/actionitemstatuses/actionitemstatusesDeleteCtrl.js",
    "/static/app/actionitemstatuses/actionitemstatusesEditCtrl.js",
    "/static/app/actionitemstatuses/actionitemstatusesListCtrl.js",
    "/static/app/actionitemstatuses/actionitemstatusesNewCtrl.js",
    "/static/app/actionitemtypes/actionitemtypesDeleteCtrl.js",
    "/static/app/actionitemtypes/actionitemtypesEditCtrl.js",
    "/static/app/actionitemtypes/actionitemtypesListCtrl.js",
    "/static/app/actionitemtypes/actionitemtypesNewCtrl.js",
    "/static/app/taskpriorities/taskprioritiesDeleteCtrl.js",
    "/static/app/taskpriorities/taskprioritiesEditCtrl.js",
    "/static/app/taskpriorities/taskprioritiesListCtrl.js",
    "/static/app/taskpriorities/taskprioritiesNewCtrl.js",
    "/static/app/taskstatuses/taskstatusesDeleteCtrl.js",
    "/static/app/taskstatuses/taskstatusesEditCtrl.js",
    "/static/app/taskstatuses/taskstatusesListCtrl.js",
    "/static/app/taskstatuses/taskstatusesNewCtrl.js",
    "/static/app/tasktypes/tasktypesDeleteCtrl.js",
    "/static/app/tasktypes/tasktypesEditCtrl.js",
    "/static/app/tasktypes/tasktypesListCtrl.js",
    "/static/app/tasktypes/tasktypesNewCtrl.js",
    "/static/app/issuepriorities/issueprioritiesDeleteCtrl.js",
    "/static/app/issuepriorities/issueprioritiesEditCtrl.js",
    "/static/app/issuepriorities/issueprioritiesListCtrl.js",
    "/static/app/issuepriorities/issueprioritiesNewCtrl.js",
    "/static/app/issuestatuses/issuestatusesDeleteCtrl.js",
    "/static/app/issuestatuses/issuestatusesEditCtrl.js",
    "/static/app/issuestatuses/issuestatusesListCtrl.js",
    "/static/app/issuestatuses/issuestatusesNewCtrl.js",
    "/static/app/issuetypes/issuetypesDeleteCtrl.js",
    "/static/app/issuetypes/issuetypesEditCtrl.js",
    "/static/app/issuetypes/issuetypesListCtrl.js",
    "/static/app/issuetypes/issuetypesNewCtrl.js",
    "/static/app/reporting_groups/reportingGroupsMainCtrl.js",
    "/static/app/reporting_naics/naicsReportingTreeDirective.js",
    "/static/app/reporting_naics/reportingNaicsMainCtrl.js",
    "/static/app/reporting_sic/sicReportingTreeDirective.js",
    "/static/app/reporting_sic/reportingSicMainCtrl.js",
    "/static/app/upload/uploadGroupDataCtrl.js",
    "/static/app/upload/uploadProgressCtrl.js",
    "/static/app/upload/uploadTestCtrl.js",
    "/static/app/reporting_components/reportingComponentsStandardsCtrl.js",
    "/static/app/reporting_components/componentReportingTreeDirective.js",
    "/static/app/reporting_components/reportingSubcomponentsCtrl.js",
    "/static/app/bronze_reporting/bronzeReportingIndexCtrl.js",
    "/static/app/bronze_reporting/bronzeReportingStartCtrl.js",
    "/static/app/bronze_reporting/bronzeReportingAccountDetailsCtrl.js",
    "/static/app/bronze_reporting/bronzeReportingUploadCtrl.js",
    "/static/app/bronze_reporting/bronzeReportingSummaryCtrl.js",
    "/static/app/bronze_reporting/bronzeReportingFormService.js",
    "/static/app/bronze_reporting/manualEnergyGridDirective.js",
    "/static/app/fileUploadButtonDirective.js",
    "/static/app/bronze_reporting_admin/bronzeReportingSubmissionsListCtrl.js"
]

temp_dir = tempfile.mkdtemp()
print(temp_dir)
file_counter = 0
for js_file in js_files:
    path = pkg_resources.resource_filename(__name__, js_file)
    new_path = os.path.join(temp_dir, str(file_counter) + ".js")
    subprocess.call(['java', "-jar", "/home/sean/compiler.jar", "--js", path, "--js_output_file", new_path])
    file_counter += 1
    print(str(file_counter))

with open("app.min.js", 'w') as outfile:
    for fc in range(0, file_counter):
        with open(os.path.join(temp_dir, str(fc) + ".js")) as infile:
            for line in infile:
                outfile.write(line)


shutil.rmtree(temp_dir)